name: update-nr-dashboard
on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        required: true
        type: string
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'

jobs:
  get_changed_endpoints_file_name:
    runs-on: ubuntu-latest
    outputs:
      fileName: ${{ steps.get-file-name.outputs.fileName }}
    steps:
      - name: Get changed endpoint file name
        id: get-file-name
        run: |
          version=$(echo ${{ inputs.releaseBranch }} | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          if [ -n "$version" ]; then
            echo "Release version is: $version"
            echo "File name is: Changed-Endpoints-$version.md"
            echo "fileName=Changed-Endpoints-$version.md" >> "$GITHUB_OUTPUT"
            cat 
          else
            echo "Parsed fail"
            exit 1
          fi
  create_dashboard:
    runs-on: ubuntu-latest
    needs: get_changed_endpoints_file_name
    steps:
      - name: Get Release wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          sparse-checkout: |
            ${{ needs.get_changed_endpoints_file_name.outputs.fileName }}
          sparse-checkout-cone-mode: false
          path: wiki
      - name: Check file
        run: |
          ls wiki
          cat wiki/${{ needs.get_changed_endpoints_file_name.outputs.fileName }}
       
