name: update-nr-dashboard
on:
  workflow_dispatch:
    inputs:
      releaseBranch:
        required: true
        type: string
        description: 'release branch name, e.g. release/1.0.0'
  pull_request:
    types:
      - closed
    branches:
      - 'release/**'

jobs:
  get_changed_endpoints_info:
    runs-on: ubuntu-latest
    outputs:
      fileName: ${{ steps.get-changed-endpoints-info.outputs.fileName }}
      releaseVersion: ${{ steps.get-changed-endpoints-info.outputs.releaseVersion }}
    steps:
      - name: Get changed endpoints info
        id: get-changed-endpoints-info
        run: |
          if [ ${{ github.event_name }} = "workflow_dispatch" ]; then            
            version=$(echo ${{ inputs.releaseBranch }} | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          else
            version=$(echo ${{ github.event.pull_request.head.ref }} | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')
          fi
          
          if [ -n "$version" ]; then
            echo "Release version is: $version"
            echo "File name is: Changed-Endpoints-$version.md"
            echo "releaseVersion=$version" >> "$GITHUB_OUTPUT"
            echo "fileName=Changed-Endpoints-$version.md" >> "$GITHUB_OUTPUT"
            cat 
          else
            echo "Parsed fail"
            exit 1
          fi
  create_dashboard:
    runs-on: ubuntu-latest
    needs: get_changed_endpoints_info
    steps:
      - name: Get Release wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          sparse-checkout: |
            ${{ needs.get_changed_endpoints_info.outputs.fileName }}
          sparse-checkout-cone-mode: false
          path: wiki
      - name: Check file
        run: |
          file=${{ needs.get_changed_endpoints_info.outputs.fileName }}
          if [ ! -e "wiki/$file" ]; then
            echo "$file doesn't exist."
          fi

      - name: Get NR tools
        uses: actions/checkout@v4
        with:
          repository: Pay-Baymax/bff-tools
          ref: master
          path: tool
          token: ${{ secrets.PERSONAL_PAT }}
      - name: Update dashboard config file
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs')
            const readline = require('readline');
            const fileName = `${{ needs.get_changed_endpoints_info.outputs.fileName }}`;
            const version = `${{ needs.get_changed_endpoints_info.outputs.releaseVersion }}`;
            
            // Read the JSON file
            const data = fs.readFileSync('tool/new-relic/dashboard-generator/config/bff-release-ci.json', 'utf8');
            const config = JSON.parse(data);
            
            // Set dashboard title
            config.title = `BFF Release ${version} - Changed Endpoints`;
            
            // Set changed endpoints
            const endpoints = config.endpoints;
            endpoints.push(`## ${version} APIs`)
            const wikiContent = fs.readFileSync(`wiki/${fileName}`, 'utf8');
            // Parse the JSON data
            wikiContent.split(/\r?\n/).forEach(line => {
              if(line.length > 0) {
                endpoints.push(line);
              }});
              
            // Write to file
            fs.writeFileSync('tool/new-relic/dashboard-generator/config/bff-release-ci.json', JSON.stringify(config, null, 2), 'utf8');
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install python-graphql-client
      - name: Publish dashboarad to NR
        env:
          NR_TOKEN: ${{ secrets.NR_TOKEN }}
        run: |
          cd tool/new-relic/dashboard-generator
          cat config/bff-release-ci.json
          python dashboard-generator.py bff-release-ci "$NR_TOKEN"        
